\begin{center}
    \Huge
    \setulcolor{orange}
    \ul{\textbf{Team-Award: Brennender Schuh}}
\end{center}
\Large

\vspace{2em}

Wir attestieren dem Team \underline{\hspace{8em} } den mit
\underline{\hspace{3cm}}km längsten zurückgelegten Weg innerhalb
der Stadt.

\vspace{1em}

\begin{center}
\includegraphics[scale=0.4]{brennender_schuh.pdf}
\end{center}

\vspace{1em}

Wir hoffen die Kultur\underline{dichte} wurde dabei nicht zu stark
vernachlässigt.

\vspace{2em}
