\begin{center}
    \Huge
    \setul{0.5ex}{0.3ex}
    \setulcolor{gray}
    \ul{\textbf{Last-in First-out Negativpreis}}
\end{center}
\Large

\vspace{2em}
Leider mussen wir für diese unökonomische Herangehensweise gegenüber Lebensmitteln
dem Team \underline{\hspace{8cm}} 10 Minuspunkte anrechnen.
\vspace{1em}

\vspace{1em}
\begin{center}
\includegraphics[scale=0.1]{lifo.pdf}
\end{center}

\vspace{2em}
