\begin{center}
    \Huge
    \setul{0.5ex}{0.3ex}
    \setulcolor{gray}
    \ul{\textbf{Schluckspecht-Preis}}
\end{center}
\Large

\vspace{2em}
Wir attestieren \underline{\hspace{8em} } die höchste
Anzahl der getrunkenen Biere, die er ordnungsgemäß über
den Harnleiter entsorgt hat. Glückwunsch\st{, Andi}!
\vspace{1em}

\vspace{1em}
\begin{center}
\includegraphics[scale=0.2]{schluckspecht.pdf}
\end{center}
\vspace{1em}

\begin{minipage}[t]{0.20\textwidth}
{\small\emph{Random Fact:}}
\end{minipage}
\begin{minipage}[t]{0.80\textwidth}
{\small Zu der Gattung der Schluckspechte (\emph{Deglutiens Picum}) gehört auch der gemeine Kackvogel (\emph{Auis Feces}).}
\end{minipage}

\vspace{2em}
