\begin{center}
    \Huge
    \setulcolor{violet}
    \ul{\textbf{Seppfred-Fischer}}

    \ul{\textbf{3-Bier Gedächtnispreis}}
\end{center}
\Large

\vspace{2em}
Wir attestieren \underline{\hspace{8em} } das Erreichen der maximalen Füllmenge
an Gerstensaft, die man in einen Salamander füllen kann.

\vspace{1em}
Oder anders gesagt: \textsc{FOTC}.

\begin{center}
\includegraphics[scale=0.15]{ok_hand.pdf}
\end{center}
\vspace{3em}
