\begin{center}
    \Huge
    \setul{0.5ex}{0.3ex}
    \setulcolor{gray}
    \ul{\textbf{Team-Award: Sommelier}}
\end{center}
\Large

\vspace{2em}
Wir attestieren dem Team \underline{\hspace{8em} } das Probieren von
\underline{\hspace{3em}} verschiedenen Bierspezialitäten. Damit ist dieses Team
im direkten Vergleich erstplatziert.

\vspace{1em}

\vspace{1em}
\begin{center}
\includegraphics[scale=0.45]{sommelier.pdf}
\end{center}

\vspace{2em}
