\begin{center}
    \Huge
    \setul{0.5ex}{0.3ex}
    \setulcolor{gray}
    \ul{\textbf{Teilnehmer-Urkunde}}
\end{center}
\Large

\vspace{2em}
\underline{\hspace{8em} } nahm erfolgreich an der Bierschnitzeljagd am \ul{~~~~\emph{4 Dezember 2021}~~~~} teil.
Wir bestätigen hiermit:
\vspace{1em}
\begin{todolist}
\item Orts und (Hefe-)Kulturkenntnisse.
\item Einen robusten Magen.
\end{todolist}

\vspace{1em}
\begin{center}
\includegraphics[scale=0.5]{scotch_hand.pdf}
\end{center}
\vspace{3em}
