\begin{center}
    \Huge
    \setulcolor{purple}
    \ul{\textbf{Teilnehmer-Urkunde}}
\end{center}
\Large

\vspace{2em}
\underline{\hspace{8em} } nahm erfolgreich an der Bierschnitzeljagd am \underline{~~~~\emph{4 Dezember 2021}~~~~} teil.
Wir bestätigen hiermit:
\vspace{1em}
\begin{todolist}
\item Orts und (Hefe-)Kulturkenntnisse.
\item Einen robusten Magen.
\end{todolist}

\vspace{1em}
\begin{center}
\includegraphics[scale=0.4]{fass.pdf}
\end{center}
\vspace{3em}
