CPU {
  Processing
}

Memory {
  Storage
}

Bottleneck: "" {
  icon: images/vn_bottleneck_gimp.png
  shape: image
  near: center-right
  width: 600
  height: 600
}

CPU <-> Memory {
  style.animated: false
}

CPU <-> Memory: Limited Bus {
  style.animated: false
}

CPU <-> Memory {
  style.animated: false
}
