matrix:
	gcc -O0 matrix.c -o matrix-bench-0
	gcc -O1 matrix.c -o matrix-bench-1
	gcc -O2 matrix.c -o matrix-bench-2
	gcc -O3 matrix.c -o matrix-bench-3

	./matrix-bench-0
	./matrix-bench-1
	./matrix-bench-2
	./matrix-bench-3
