employee:
	gcc -O0 employee.c -o employee-bench-0
	gcc -O1 employee.c -o employee-bench-1
	gcc -O2 employee.c -o employee-bench-2
	gcc -O3 employee.c -o employee-bench-3

	./employee-bench-0
	./employee-bench-1
	./employee-bench-2
	./employee-bench-3
