#!/bin/bash

go run main.go \
    --output /tmp/wp.mkv \
    --frames-per-second 24 \
    --blend-duration 5s \
    --key-duration 1s \
    --input ~/code/dotfiles/wallday/0.png \
    --input ~/code/dotfiles/wallday/1.png \
    --input ~/code/dotfiles/wallday/2.png \
    --input ~/code/dotfiles/wallday/3.png \
    --input ~/code/dotfiles/wallday/4.png \
    --input ~/code/dotfiles/wallday/5.png \
    --input ~/code/dotfiles/wallday/6.png \
    --input ~/code/dotfiles/wallday/7.png \
    --input ~/code/dotfiles/wallday/8.png \
    --input ~/code/dotfiles/wallday/9.png \
    --input ~/code/dotfiles/wallday/10.png \
    --input ~/code/dotfiles/wallday/11.png \
    --input ~/code/dotfiles/wallday/12.png \
    --input ~/code/dotfiles/wallday/13.png \
    --input ~/code/dotfiles/wallday/14.png \
    --input ~/code/dotfiles/wallday/15.png \
    --input ~/code/dotfiles/wallday/16.png \
    --input ~/code/dotfiles/wallday/17.png \
    --input ~/code/dotfiles/wallday/18.png \
    --input ~/code/dotfiles/wallday/19.png \
    --input ~/code/dotfiles/wallday/20.png \
    --input ~/code/dotfiles/wallday/21.png \
    --input ~/code/dotfiles/wallday/22.png \
    --input ~/code/dotfiles/wallday/23.png \
