direction: right

before {
  log: Log (100 MB)
  reader <- log
  writer -> log: append
}

after {
  data {
    s1: segment_1 (32 MB)
    s2: segment_2 (32 MB)
    s3: segment_3 (32 MB)
    log: Log (4 MB)
  }

  reader <- data.s1
  reader <- data.s2
  reader <- data.s3
  reader <- data.log

  compactor -> data.s1
  compactor -> data.s2
  compactor -> data.s3
  writer -> data.log: append
}
