// Get Polylux from the official package repository
#import "@preview/polylux:0.4.0": *
#import "@preview/cetz:0.3.2"


#enable-handout-mode(false)

// Can be used to embed speaker notes.
// We define this locally instead of using `toolbox.pdfpc.speaker-note`
// because polylux 0.4.0 still does `type(x) == "string"` checks, which
// silently broke when typst 0.12+ changed `type()` to return type objects.
#let comment(body) = {
  let txt = if type(body) == str {
    body
  } else if type(body) == content and body.func() == raw {
    body.text.trim()
  } else {
    panic("comment(): expected a string or a raw block")
  }
  [ #metadata((t: "Note", v: txt)) <pdfpc> ]
}

// Rainbow-colour each codepoint of a string. Inherits font size/weight
// from the surrounding text() so it composes cleanly inside headlines.
#let rainbow(s) = {
  let colors = (
    rgb("#e74c3c"), // red
    rgb("#e67e22"), // orange
    rgb("#f39c12"), // amber
    rgb("#27ae60"), // green
    rgb("#2980b9"), // blue
    rgb("#8e44ad"), // purple
  )
  for (i, c) in s.codepoints().enumerate() {
    text(fill: colors.at(calc.rem(i, colors.len())))[#c]
  }
}

#show link: set text(blue)
#set text(font: "TT2020 Style E", size: 20pt)
// #show raw: set text(font: "Fantasque Sans Mono")

// #set heading(numbering: "I.")


// Make the paper dimensions fit for a presentation and the text larger
#set page(
  paper: "presentation-16-9",
  footer: [
    #set text(fill: gray, size: .8em)
    #set align(horizon)

    Chris Pahl, 2026 #h(1fr) #toolbox.slide-number
  ],
  header: box(inset: 8pt)[
    #set align(horizon)
    #set text(size: .6em)

    #show link: it => {
      set text(fill: black)
      strong(it.body)
    }
    #set text(fill: gray)

    #toolbox.progress-ratio(ratio => [
      #let progress = calc.round(ratio * 100)
      #if progress > 0 [
        #progress%
      ]
    ])
    #h(1fr)
  ]
)

#slide[
  #comment(```md
  - Welcome the audience. Briefly say what this is NOT: a dunk on AI.
  - It's about finding the right place on the spectrum and not handing
    over more control than we mean to.
  - ~30 min, plenty of room for discussion after.
```)

  // Title slide layout: full-slide-height illustration anchored to the
  // right; title text in the remaining space on the left. The image is
  // portrait (~9:10) on a 16:9 slide, so it occupies roughly the right
  // half and leaves room for the title without covering the figure.
  // Margin is zeroed so the image truly bleeds to the slide edges.
  #set page(footer: none, header: none, margin: 0pt)

  #place(right + horizon, image("images/zauberlehrling.png", height: 100%))

  #place(left + horizon, box(width: 50%, inset: 2em)[
    #text(size: 2.2em, weight: "bold")[The #rainbow("vibes")\ that I summoned...]

    #v(1em)
    #text(size: .95em, fill: gray)[
      Thoughts on working\
      with AI agents.
    ]

    #v(2.5em)
    #text(size: .85em)[Chris Pahl · 2026]
  ])
]


#slide[
  #comment(```md
  - I spend sometimes unreasonable amount of time on Reddit
  - There are tons like sub-reddits that can be roughly placed on the
    spectrum. r/BetterOffline (left) or r/singularity (right)
  - Words like "AI slop" or "cope" is thrown around like confetti.
  - I just sit there in between and think, how so often in life,
    that both extremes are pretty weird.
  - The consensus is though, at least when it comes to software development,
    that there is a tradeoff between control and productivity.
```)

  = The Spectrum (on Reddit)

  #v(1.5em)
  #align(center)[
    #cetz.canvas(length: 1cm, {
      import cetz.draw: *

      let bar-w = 18
      let bar-h = 0.6

      // gradient bar: green (control / quality) → red (loss of control)
      rect(
        (0, -bar-h/2), (bar-w, bar-h/2),
        fill: gradient.linear(
          blue, green, red,
        ),
        stroke: 1pt + black,
      )

      // tick marks
      for x in (0,  bar-w) {
        line((x, -bar-h/2 - 0.15), (x, bar-h/2 + 0.15), stroke: 1.5pt + black)
      }

      // sweet-spot marker (slightly left of centre — bias toward control)
      let mx = bar-w * 0.42

      // endpoint labels
      content((0, -1.2), [*Full manual*])
      content((0, -1.8), text(size: .75em, fill: gray)[every keystroke yours])
      content((bar-w, -1.2), [*Full vibecode*])
      content((bar-w, -1.8), text(size: .75em, fill: gray)[just make it work])

      // bottom axis annotations
      content(
        (bar-w/2, -3.0),
        text(size: .85em, fill: gray)[
          #v(1cm)
          ⟵ more control · more understanding | more productivity · more delegation ⟶
        ],
      )
    })
  ]

  #v(.5em)
  #align(center)[
    #v(1cm)
    #text(fill: gray)[General tendency:]

    Using GenAI is a tradeoff between control and productivity.
  ]
]

#slide[
  #comment(```md
Why is there another duck? I didn't choose the background. Wtf.

Code generated by AI can be seen a bit like generated images - hard to do adjustments because you don't have the photoshop file with layers and knowledge what you need to change with what effect.

You can do 80% of the result in sceonds, but the 20% left for a good result
require 80% of the skill.
  ```)
  
  #place(left + horizon, box(width: 40%, inset: 0em)[
    #text(fill: gray)[Prompt:] \
    "Imagine Donald Duck as realistic human. Remove the hat."
  ])


  #align(right+horizon)[
    #image("images/aifail.jpg")
  ]
]

#slide[
  #comment(```md
  Which brings me to the core of my take:

  Three curves on the same X-axis (manual → vibecode).

  - Quality: starts middling (humans are flawed too!), rises with judicious
    AI assistance, then falls off a cliff when nobody is reading the diff.
  - Productivity: low on full manual, climbs through the middle, peaks
    just right of centre — and then *falls again* as quality issues create
    rework. (METR 2025: experienced devs were 19% SLOWER with AI on their
    own mature OSS repos, while predicting +24% speed-up.)
  - Confidence: the dangerous curve. High on manual (you wrote it, you
    know it), dips in the middle (you're humble, you verify), spikes on
    the right where it *decouples from reality*. (Perry et al. 2023:
    devs using AI assistants wrote less secure code AND were more
    confident the code was correct.)
  - The widening gap between confidence (green) and quality (blue) on
    the right is the most important thing on this slide. That's the
    Dunning-Kruger zone.
```)

  = My take: Quality vs Productivity

  #v(.5em)
  #align(center)[
    #cetz.canvas(length: 1cm, {
      import cetz.draw: *

      let w = 14
      let h = 6

      // Danger-zone tint: the right 25% of the chart (Dunning-Kruger territory).
      let danger-x = w * 0.75
      let danger-red = rgb("#d9542b")
      rect(
        (danger-x, 0),
        (w, h),
        fill: danger-red.transparentize(82%),
        stroke: none,
      )

      // axes
      line((0, 0), (w + 0.4, 0), stroke: 1pt + black, mark: (end: ">"))
      line((0, 0), (0, h + 0.4), stroke: 1pt + black, mark: (end: ">"))

      // x labels
      content((0, -0.5), [manual])
      content((w, -0.5), [vibecode])
      content((w/2, -1.1), text(fill: gray, size: .8em)[← how much you delegate to the model →])

      // y label
      content((-0.4, h + 0.3), text(size: .8em, fill: gray)[high], anchor: "east")
      content((-0.4, 0.3), text(size: .8em, fill: gray)[low], anchor: "east")

      // Quality curve: starts mid, peaks in middle, drops at right
      let q-color = rgb("#1f77b4")
      hobby(
        (0, 3.0),
        (3, 4.0),
        (6, 5.2),
        (9, 4.6),
        (12, 2.6),
        (w, 1.2),
        stroke: 2.5pt + q-color,
      )

      // Productivity curve: low → peaks just right of centre → falls again
      // (rework from quality issues eats the perceived gains)
      let p-color = rgb("#d9542b")
      hobby(
        (0, 0.8),
        (3, 2.0),
        (6, 4.0),
        (9, 5.0),
        (12, 4.0),
        (w, 1.8),
        stroke: 2.5pt + p-color,
      )

      // Confidence curve: high on manual (calibrated), humble in the middle,
      // *falsely* ultra-high on the vibecode side (Dunning–Kruger zone)
      let c-color = rgb("#3a8f4a")
      hobby(
        (0, 4.0),
        (3, 3.5),
        (6, 3.2),
        (9, 4.0),
        (12, 5.2),
        (w, 6.0),
        stroke: 2.5pt + c-color,
      )

      // inline curve labels (no legend — cleaner)
      content((2.3, 4.6), text(weight: "bold", fill: q-color)[Quality])
      content((9.7, 5.5), text(weight: "bold", fill: p-color)[Productivity])
      content((7.0, 2.8), text(weight: "bold", fill: c-color)[Confidence])

      // sweet-spot marker at the apex of the Quality curve
      let sx = 6.0
      let sy = 5.18
      circle((sx, sy), radius: 0.14, fill: black)
      line((sx, sy + 0.15), (sx, sy + 0.9), stroke: 0.7pt + gray)
      content((sx, sy + 1.2), text(size: .85em, fill: gray, style: "italic")[sweet spot])

      // gap annotation on the right edge: confidence (6.0) vs quality (1.2)
      // a thin bracket showing the dangerous divergence
      let gx = w - 0.3

      // Dotted red separator at the danger-zone boundary, drawn last so it
      // stays visible on top of the curves.
      line(
        (danger-x, 0),
        (danger-x, h + 0.2),
        stroke: (paint: danger-red, dash: "dotted", thickness: 1.4pt),
      )
    })
  ]

  #v(.3em)
  #align(center)[
    #text(size: .85em, fill: gray)[
      #text(fill: rgb(220, 80, 0))[Danger Zone:] Dunning-Kruger
    ]
  ]
]

#slide[
  #comment(```md
  Card-by-card:

  -19% (METR, 2025). Randomised controlled trial. 16 experienced OSS devs,
  246 real tasks in their OWN mature repos, ~5 yr experience each. With
  Cursor + Claude 3.5/3.7 they were 19% slower. They PREDICTED +24% faster
  beforehand; even afterward they still BELIEVED they'd been ~20% faster.
  The perception-reality gap is the real finding.

  ~40% (NYU, 2021 — "Asleep at the Keyboard?"). Tested Copilot on 89
  scenarios in security-relevant settings. ~40% of generated programs
  contained exploitable bugs. The original alarm bell; replicated since.

  8x (GitClear, 2024). Analysis of 211M changed lines, 2020-2024.
  Duplicated code blocks rose ~8x. Refactored ("moved") lines fell from
  24% → 10%. Churn (lines rewritten within 2 weeks) rose 5.5% → 7.9%.
  Translation: AI nudges devs to copy-paste instead of refactor.

  -7.2% (DORA / Google Cloud, 2024). State-of-DevOps survey. AI adoption
  correlated with 1.5% throughput drop AND 7.2% stability drop. 39% of
  respondents reported little-to-no trust in AI-generated code. This is
  the broadest dataset we have.

  29.5% (Fu et al., ACM TOSEM 2025). Empirical study: 29.5% of AI-generated
  Python snippets and 24.2% of JavaScript snippets contained known CWEs
  (Common Weakness Enumeration entries). Replicates and quantifies the
  NYU finding.

  ↓ critical thinking (Lee et al., CHI 2025, Microsoft + CMU). 319
  knowledge workers, 936 first-hand examples. Finding: higher confidence
  in GenAI is associated with LESS critical thinking. Higher self-confidence
  is associated with MORE. Ties directly to the cog-biases slide.
```)

  = But there's already data:

  #v(.6em)

  // Stat-card helper. Glanceable — audience feels the volume, doesn't read.
  #let card(stat, headline, body, source, color: rgb("#c0392b")) = box(
    width: 100%,
    inset: (left: .8em, right: .6em, y: .35em),
    stroke: (left: 4pt + color),
    [
      #text(size: 1.6em, weight: "bold", fill: color)[#stat]
      #v(-.4em)
      #text(size: .85em, weight: "bold")[#headline] \
      #text(size: .6em, fill: gray)[#body] \
      #v(.1em)
      #text(size: .55em, fill: gray, style: "italic")[#source]
    ]
  )

  #grid(
    columns: (1fr, 1fr, 1fr),
    rows: (1fr, 1fr),
    column-gutter: .8em,
    row-gutter: .8em,

    card(
      [−19%],
      [slower with AI],
      [experienced devs · own mature repos · predicted +24%],
      [METR · RCT · 2025],
    ),
    card(
      [∼40%],
      [insecure programs],
      [Copilot output across 89 security-relevant scenarios],
      [NYU CCS · 2021],
    ),
    card(
      [8×],
      [more duplicated code],
      [block-level clones up · refactoring 24% → 10%],
      [GitClear · 211M LoC · 2024],
    ),

    card(
      [−7.2%],
      [delivery stability],
      [drop with AI adoption · 39% distrust AI code],
      [DORA / Google · 2024],
      color: rgb("#444444"),
    ),
    card(
      [29.5%],
      [Python with CWEs],
      [AI-generated code in real GitHub repos · 43 CWE categories],
      [Fu et al. · ACM TOSEM · 2025],
    ),
    card(
      [↓],
      [trust = less scrutiny],
      [more trust in GenAI ⇒ less critical thinking applied],
      [Lee et al. · Microsoft + CMU · CHI 2025],
      color: rgb("#444444"),
    ),
  )
]

// Tag helper: a single keyword, given a size, rotation, and colour.
// Flowing layout (not absolute placement) so adding/removing tags
// re-wraps cleanly. Heaviest risks get colour + bold.
#let tag(sz, body, color: black, angle: 0deg, weight: "regular") = box(
  inset: (x: .35em, y: .25em),
  rotate(angle, text(size: sz, fill: color, weight: weight)[#body]),
)

#set par(leading: .9em, justify: false)

#slide[
  #comment(```md
  Flip side of the risks slide — and the bridge into "maybe it's how we use it".
  Green = the ones where AI genuinely earns its keep: low cost of being wrong,
  high cost of doing it by hand, and a human still owns the result.

  Cognitive scaffolding (green):
  - Rubber-ducking: explain it out loud, find the bug.
  - Explaining unfamiliar code: faster than archaeology.
  - Edge case brainstorming: "what could go wrong?"
  - Learning accelerator: ramp-up on new languages/libraries.
  - Naming things: the second-hardest problem in CS, suddenly cheap.

  Cheap-to-verify drafting:
  - Boilerplate, fixtures, mock data.
  - Test generation, regex / SQL.
  - Documentation drafts, commit messages, changelogs.
  - Translation between languages (human and programming).

  Search & comprehension:
  - Code review companion, error decoding, log analysis.
  - Summarising long PRs / threads / docs.
  - Onboarding ramp-up for new team members.
```)

  = Use-cases that could make us better devs

  #let green = rgb("#3a8f4a")
  #let mid = rgb("#444444")
  #let pale = rgb("#888888")

  #align(center + horizon)[
    #tag(1.6em, [rubber-ducking], color: green, angle: -2deg, weight: "bold")
    #tag(.9em, [ideation], color: pale, angle: -3deg)
    #tag(1.5em, [explain unfamiliar code], color: green, angle: +2deg, weight: "bold")
    #tag(1.0em, [test generation], color: mid, angle: -1deg)
    #tag(1.4em, [pair programming], color: green, angle: +1deg, weight: "bold")
    #tag(.9em, [boilerplate], color: pale, angle: +2deg)
    #tag(1.15em, [refactoring assist], color: mid, angle: -2deg)
    #tag(1.45em, [learning accelerator], color: green, angle: -3deg, weight: "bold")
    #tag(1.0em, [documentation drafts], color: mid, angle: +3deg)
    #tag(.9em, [naming things], color: pale, angle: +1deg)
    #tag(1.05em, [summarisation], color: mid, angle: -1deg)
    #tag(.85em, [regex / SQL crafting], color: pale, angle: +2deg)
    #tag(1.3em, [edge-case brainstorming], color: green, angle: -1deg, weight: "bold")
    #tag(.9em, [translation], color: pale, angle: +3deg)
    #tag(1.1em, [code review companion], color: mid, angle: -2deg)
    #tag(.85em, [mock data / fixtures], color: pale, angle: +2deg)
    #tag(.95em, [error decoding], color: pale, angle: -1deg)
    #tag(1.1em, [search engine], color: mid, angle: +1deg)
    #tag(.9em, [log analysis], color: pale, angle: -3deg)
    #tag(.85em, [proofreading], color: pale, angle: +2deg)
    #tag(1.0em, [automation], color: mid, angle: -2deg)
  ]
]

#slide[
  #comment(```md
  Rapid-fire — don't dwell on any one. Goal: land the cumulative weight
  before pivoting to "but maybe it's how we use it".

  Societal & infrastructure:
  - Ecological cost: training and inference burn power and water.
  - Hardware crisis: GPU demand distorts supply for everyone.
  - Concentration: a handful of companies own the server farms.
  - Economic transfer: value flows from many small actors to a few large ones.

  Trust, legal, security:
  - Data privacy: "trust me, bro" is not a threat model.
  - Licensing: models can regurgitate GPLv3 / proprietary code verbatim.
  - Operator bias: models can be tuned to express the values of whoever runs them (Hi Grok!).
  - Prompt injection & MCP: a whole new attack class.
  - Cyberattack automation: phishing, social engineering, deepfakes at scale.

  Information ecosystem:
  - Misinformation at scale: generation cheaper than fact-checking.
  - Content degradation: the open web fills with AI slop.
  - Recursive collapse: tomorrow's models train on yesterday's slop.
  - Communities thinning out: SO, OSS Q&A, mailing lists — fewer humans.

  Workforce & cognition:
  - Fewer juniors hired: no juniors today → no seniors tomorrow.
  - Atrophy: skills you don't use, you lose. (See: calculators, navigation without Google Maps.)
  - Schools: AI can boost or bypass learning (more on this in a moment).
  - Convincing hallucinations: the failure mode that will eventually kill someone.
```)

  = Risks for all

  #let red = rgb("#c0392b")
  #let mid = rgb("#444444")
  #let pale = rgb("#888888")

  #align(center + horizon)[
    #tag(.85em, [ecological cost], color: pale, angle: -3deg)
    #tag(1.7em, [Convincing hallucinations], color: red, angle: -2deg, weight: "bold")
    #tag(.8em, [education], color: pale, angle: +3deg)
    #tag(1.1em, [licensing], color: mid, angle: -2deg)
    #tag(1.55em, [Atrophy], color: black, angle: +2deg, weight: "bold")
    #tag(.85em, [concentration], color: pale, angle: +1deg)
    #tag(1.15em, [misinformation at scale], color: mid, angle: -1deg)
    #tag(1.45em, [Prompt injection & MCP], color: red, angle: +3deg, weight: "bold")
    #tag(.9em, [content degradation], color: pale, angle: -2deg)
    #tag(1.6em, [No juniors hired], color: black, angle: -1deg, weight: "bold")
    #tag(1.0em, [hardware crisis], color: mid, angle: +2deg)
    #tag(1.1em, [operator bias], color: mid, angle: -3deg)
    #tag(1.2em, [recursive collapse], color: mid, angle: +1deg)
    #tag(.85em, [economic transfer], color: pale, angle: -2deg)
    #tag(1.25em, [data privacy], color: red, angle: +2deg)
    #tag(1.05em, [cyberattack automation], color: mid, angle: -1deg)
    #tag(.85em, [communities thinning out], color: pale, angle: +3deg)
    #tag(1.45em, [erosion of trust], color: red, angle: +3deg, weight: "bold")
  ]
]

#slide[
  = Risks for us
  #let mid = rgb("#444444")
  #let pale = rgb("#888888")
  #let red = blue

  #align(center + horizon)[
    #tag(.85em, [ecological cost], color: pale, angle: -3deg)
    #tag(1.7em, [Convincing hallucinations], color: blue, angle: -2deg, weight: "bold")
    #tag(.8em, [education], color: blue, angle: +3deg)
    #tag(1.1em, [licensing], color: blue, angle: -2deg)
    #tag(1.55em, [Atrophy], color: blue, angle: +2deg, weight: "bold")
    #tag(.85em, [concentration], color: blue, angle: +1deg)
    #tag(1.15em, [misinformation at scale], color: mid, angle: -1deg)
    #tag(1.45em, [Prompt injection & MCP], color: blue, angle: +3deg, weight: "bold")
    #tag(.9em, [content degradation], color: pale, angle: -2deg)
    #tag(1.6em, [No juniors hired], color: blue, angle: -1deg, weight: "bold")
    #tag(1.0em, [hardware crisis], color: blue, angle: +2deg)
    #tag(1.1em, [operator bias], color: mid, angle: -3deg)
    #tag(1.2em, [recursive collapse], color: mid, angle: +1deg)
    #tag(.85em, [economic transfer], color: pale, angle: -2deg)
    #tag(1.25em, [data privacy], color: blue, angle: +2deg)
    #tag(1.05em, [cyberattack automation], color: blue, angle: -1deg)
    #tag(.85em, [communities thinning out], color: blue, angle: +3deg)
    #tag(1.45em, [erosion of trust], color: mid, angle: +3deg, weight: "bold")
  ]
]


#slide[
  #comment(```md
  - Deliberately re-frame: we've just listed a lot of scary things, but
    most of them are about *how* AI is deployed, not whether it exists.
  - Schools are a clean case study because the same tool produces opposite
    outcomes depending on use.
```)

  #set align(center + horizon)

  #text(size: 1.5em)[Exhibit A: Education]

  #v(2em)
  #text(size: 1.3em, style: "italic", fill: gray)[
    Maybe it's not so much about the tool —\
    but about how we use it?
  ]
]


#slide[
  #comment(```md
  Bastani et al. Wharton/Penn field experiment, ~1000 Turkish high-school
  maths students. The cleanest piece of evidence we have on tutor-vs-solver.

  Three groups:
  - Control:    no AI, do the work yourself.
  - AI solver:  asks ChatGPT, gets the answer.
  - AI tutor:   asks a tutor-prompted ChatGPT, gets a hint.

  During practice (with the tool available):
  - Solver group ≈ +48% over control.
  - Tutor group  ≈ +127% over control.
  - Both look like they're crushing it.

  On the unaided exam (no AI):
  - Solver group ≈ -17% vs control. They got WORSE than students who never
    used AI at all. They had learned to operate the tool, not the maths.
  - Tutor group  ≈ ±0% vs control — at least no harm.

  The kicker: same model, same students, same maths. The only thing that
  changed was *what they used the AI for*. Hint-mode preserved learning;
  answer-mode actively damaged it.

  Talking points:
  - "Practice performance" is what most of us optimise for in our day-to-day
    AI usage — code that ships, tickets closed. That's the tall light bars.
  - "Unaided exam" is what happens when the AI is down, or when you switch
    teams, or when the problem is genuinely novel. That's the dark bars.
  - For developers the parallel is direct: if you use AI to solve, you'll
    pass code review while it's available. The day it isn't, the gap shows.

  Backup source: Lee et al., CHI 2025 (Microsoft + CMU) — surveyed knowledge
  workers; the more they trusted GenAI, the less critical thinking they
  reported applying.

  VERIFY exact numbers and SSRN ID before presenting.
```)

  = Study: AI in school lessons

  #v(1cm)

  #align(center)[
    #cetz.canvas(length: 1cm, {
      import cetz.draw: *

      // Bastani et al., ~1000 Turkish high-school maths students.
      // Practice gain over control: Solver ≈ +48%, Tutor ≈ +127%.
      // Unaided exam vs control:    Solver ≈ -17%, Tutor ≈ ±0%.
      // VERIFY exact numbers before presenting.
      let baseline = 2.2

      // 3 groups × (practice-height, exam-height, group colour, label)
      let groups = (
        (2.2, 2.2, gray, [No AI\ #text(size: .7em, fill: gray)[control]]),
        (3.25, 1.53, rgb("#c0392b"), [AI as #strong[solver]\ #text(size: .7em, fill: gray)[gives the answer]]),
        (5.0, 2.3, rgb("#1f77b4"), [AI as #strong[tutor]\ #text(size: .7em, fill: gray)[gives a hint]]),
      )

      let w = 18
      let h = 5.6
      let bw = 0.9
      let gap = 0.15
      let group-gap = w / 3
      let x0 = group-gap / 2

      // y-axis
      line((0, 0), (0, h), stroke: 1pt + black, mark: (end: ">"))
      content((-0.4, h - 0.2), text(size: .75em, fill: gray)[score], anchor: "east")

      // control baseline (drawn before bars so they overlap it)
      line((0, baseline), (w, baseline), stroke: (dash: "dashed", paint: gray, thickness: 0.8pt))
      line((0, 0), (w, 0), stroke: 1pt + black, mark: (end: ">"))

      //content((w - 0.1, baseline - 0.4), anchor: "east",
      //        text(size: .7em, fill: gray)[control baseline])

      // bars
      for (i, g) in groups.enumerate() {
        let (p-h, e-h, color, label) = g
        let xc = x0 + i * group-gap

        rect((xc - bw - gap/2, 0), (xc - gap/2, p-h),
             fill: color.lighten(70%), stroke: 1pt + color)
        rect((xc + gap/2, 0), (xc + bw + gap/2, e-h),
             fill: color, stroke: 1pt + color)

        content((xc, -1), label)
      }

      // legend (upper-left interior, in the empty space before the first group)
      let lx = 0.6
      let ly = h - 0.3
      rect((lx, ly - 0.4), (lx + 0.45, ly - 0.05),
           fill: gray.lighten(70%), stroke: 1pt + gray)
      content((lx + 0.6, ly - 0.225), anchor: "west", text(size: .7em)[during practice])
      rect((lx, ly - 1.0), (lx + 0.45, ly - 0.65),
           fill: gray, stroke: 1pt + gray)
      content((lx + 0.6, ly - 0.825), anchor: "west", text(size: .7em)[on unaided exam])
    })
  ]

  #v(.3em)
  #align(center)[
    #text(size: .65em, fill: gray)[
      Bastani et al., _Generative AI Can Harm Learning_, SSRN 2024 
    ]

    #text(size: .65em, fill: gray)[
      Pupils did prefer to be in the solver group though...  :-(
    ]
  ]
]


#slide[
  #set page(footer: none)
  #v(4cm)
  #align(center)[
    #text(size: 1.9em)[Are #emph[you] team tutor or team solver?]
  ]
]

#slide[
  #comment(```md
  This slide is *automation bias, with our own receipt*. It sets up the
  bias cards that follow.

  Two numbers, both from our team's Claude Code dashboard, April 2026:
  - 98.7% suggestion acceptance rate. If a junior's PRs landed at 98.7%
    accepted as-is, we'd be worried about whether the review was real.
  - 27,757 lines accepted in one month. ≈ 925 lines per working day.

  Reality check on review capacity:
  - Industry rule of thumb for *careful* code review: ~100–200 LoC/hour
    (Cohen, *Best Kept Secrets of Peer Code Review*; Google's internal
    guidance is in the same ballpark).
  - 27,757 lines would take ~138 hours of careful review.
  - A working month is ~176 hours. ~38 hours left for everything else
    — design, debugging, meetings, actually writing the code we're NOT
    accepting from Claude.
  - We did not spend 138 hours reviewing.

  Don't be defensive — it's not about our team being lazy. It's about
  what 98.7% *necessarily* means: most acceptances are not carefully
  reviewed acceptances. They can't be. There aren't enough hours in the
  month.

  Tee up the biases section: this is the data behind why automation
  bias matters in practice.
```)

  = Keeping up with Claude

  #v(.2em)
  #align(center)[
    #text(size: .85em, fill: gray)[Our team's Claude Code account · April 2026]
  ]

  #v(.6em)

  #grid(
    columns: (1fr, 1fr),
    column-gutter: 1.5em,
    align: horizon,

    box(
      width: 100%,
      inset: (left: 1.2em, right: 1em, y: .5em),
      stroke: (left: 6pt + rgb("#c0392b")),
      [
        #text(size: 3.6em, weight: "bold", fill: rgb("#c0392b"))[98.7%]
        #v(-.5em)
        #text(size: .9em, weight: "bold")[suggestions accepted as-is] \
        #text(size: .6em, fill: gray)[1.3% rejected.]
      ]
    ),
    box(
      width: 100%,
      inset: (left: 1.2em, right: 1em, y: .5em),
      stroke: (left: 6pt + black),
      [
        #text(size: 3.6em, weight: "bold")[27,757]
        #v(-.5em)
        #text(size: .9em, weight: "bold")[lines accepted last month] \
        #text(size: .6em, fill: gray)[≈ 925 LoC/day \
          careful review ≈ 100–200 LoC/hour]
      ]
    ),
  )

  #v(.6em)
  #align(center)[
    #text(size: .85em)[
      Reviewing 27,757 lines carefully ≈ *138 h*.
    ]
  ]
]

// Bias-card helper used on both bias slides. Same visual rhythm as the
// stat cards on the Studies slide, with three fields: name (the "stat"),
// short definition, and an italic LLM-specific cue underneath.
#let bias-card(name, defn, hook, color) = box(
  width: 100%,
  inset: (left: .8em, right: .6em, y: .25em),
  stroke: (left: 4pt + color),
  [
    #text(size: 1.05em, weight: "bold", fill: color)[#name]
    #v(-.3em)
    #text(size: .7em)[#defn] \
    #v(.05em)
    #text(size: .6em, fill: gray, style: "italic")[#hook]
  ]
)

#slide[
  #comment(```md
  These are *our* biases — defaults wired into how humans process
  suggestions from an authoritative-sounding source. They aren't new;
  LLMs just hit each of them harder than almost any tool before.

  Card-by-card:

  - Automation bias. We accept machine suggestions more readily than human
    ones. GitHub reports ~30% of Copilot suggestions accepted as-is (VERIFY).
    Combine that with how often we even read the diff.

  - Anchoring. The first suggestion shapes the solution space. LLMs
    suggest fast, so they almost always get to anchor first — your
    "thinking" then becomes refining their idea rather than generating
    your own.

  - Confirmation bias. The prompt we type already contains the answer
    we want. Phrasing alone often determines what comes back.

  - Authority bias. Eloquent + fast + confident reads as expert. LLMs
    are eloquent, fast, AND confident — even when wrong. We're not
    wired to discount fluency.

  - Dunning–Kruger, remixed. Users mistake the model's competence
    for their own. Dangerous for seniors and juniors alike. The senior
    thinks "this is what I'd have written"; the junior thinks "I now
    understand this codebase".

  - Illusion of explanatory depth. We think we understand something
    until asked to explain it. Maths teachers know. AI-generated code
    we've reviewed but not WRITTEN sits squarely in this trap.

  Not on the slide but worth mentioning:
  - Atrophy. Not a bias — the *cumulative effect* of the others over
    months. Skills decay quietly.

  Plug: full talk on cognitive biases coming next time I'm in Augsburg.
```)

  = Human cognitive biases

  #v(.4em)

  #let hb = rgb("#7d3c98")  // human-bias accent (violet)

  #grid(
    columns: (1fr, 1fr, 1fr),
    rows: (1fr, 1fr),
    column-gutter: .8em,
    row-gutter: .8em,

    bias-card(
      [Automation bias],
      [We accept machine suggestions more readily than human ones.],
      [click accept · review later · maybe],
      hb,
    ),
    bias-card(
      [Anchoring],
      [The first suggestion shapes the solution space — even when it's wrong.],
      [the model frames the problem before you do],
      hb,
    ),
    bias-card(
      [Confirmation bias],
      [We hear what we already believe.],
      [the prompt contains the answer we want],
      hb,
    ),

    bias-card(
      [Authority bias],
      [Eloquent + fast + confident = reads as expert.],
      [fluency ≠ correctness],
      hb,
    ),
    bias-card(
      [Dunning–Kruger],
      [We mistake competence we observe for competence we have.],
      ["this is what I would have written"],
      hb,
    ),
    bias-card(
      [Illusion of explanatory depth],
      [We think we understand — until asked to explain.],
      [Reading diffs is not enough!],
      hb,
    ),
  )
]


#slide[
  #comment(```md
  Flip side: the model has its *own* biases, baked in statistically by
  the training process. Different shape from human biases, same outcome:
  the answer you get is not the answer you'd derive from first principles.

  Card-by-card:

  - Sycophancy. It's easy to talk the model out of a correct answer.
    Push back hard and it caves, even when right. RLHF training rewards
    apparent helpfulness, which correlates with agreement. Echo chambers
    but for code: ask twice the way you wanted, get the answer you wanted.

  - Historical / representation bias. Trained on the open web —
    overwhelmingly modern, English-speaking, Western. Defaults are
    weighted toward what's most COMMON, not what's most correct for
    YOUR codebase.

  - Attention bias. The first and last things you say dominate. The
    middle of a long context evaporates. Long system prompts + long
    files = unpredictable adherence to the rules buried in the middle.

  - Omission bias. Rare and novel answers are statistically suppressed
    by common ones in training data. The model is bad at being weird.
    If your problem requires an unusual answer, the model gravitates
    to the safe-but-wrong one.

  Tying it back: the human biases and the model biases compound. We
  trust the fluent-sounding output (authority + automation); it tends
  toward the common answer (omission + historical); we don't push
  back (confirmation + the model's sycophancy completing the loop).
```)

  = Statistical model biases

  #v(.4em)

  #let mb = rgb("#117a65")  // model-bias accent (teal)

  #grid(
    columns: (1fr, 1fr),
    rows: (1fr, 1fr),
    column-gutter: .8em,
    row-gutter: .8em,

    bias-card(
      [Sycophancy],
      [It's easy to talk the model out of a correct answer.],
      [echo chambers — but for code],
      mb,
    ),
    bias-card(
      [Historical / representation bias],
      [Trained on the web — heavily modern, English, Western.],
      [defaults track what's common, not what's right],
      mb,
    ),
    bias-card(
      [Attention bias],
      [First and last things dominate; the middle evaporates.],
      [rules buried in long context get ignored],
      mb,
    ),
    bias-card(
      [Omission bias],
      [Rare and novel answers get suppressed by common ones.],
      [the model is bad at creative solutions],
      mb,
    ),
  )
]

#slide[
  #comment(```md
  - This is the slide that should make the room uncomfortable for a
    second. The juniors-not-hired problem isn't just an economics
    problem — it's a *verification* problem.
  - If you don't know what good code looks like, you can't prompt for it.
  - If you don't understand the diff, you can't review it.
```)

  = Hen & Egg questions

  #v(1em)
  #set text(size: 1.1em)

  1. If you don't know what good software looks like — \
    #text(fill: gray)[#emph[how do you write the right prompt?]]

  #v(.6em)

  2. If you can't understand what the model just generated — \
    #text(fill: gray)[#emph[how do you verify it?]]

  #v(.6em)

  3. If you can't code (anymore) — \
    #text(fill: gray)[#emph[how can you understand the diffs?]]

  #v(.6em)

  4. If you do not know what you build inside-out — \
     #text(fill: gray)[#emph[how do you learn new designs?]]
]

#slide[
  #v(4cm)
  #align(center)[
    #text(size: 2em)[How do #emph[you] keep up with Claude?]
  ]
]

#slide[
  #comment(```md
  - Frame the next few slides: not commandments, just a small set of
    habits that have worked for me and that survive contact with reality.
```)

  = Five habits that helped me

  #v(.8em)

  #let green = rgb("#3a8f4a")

  #let habit(num, body, color: green) = box(
    width: 100%,
    inset: (left: 1em, right: .8em, y: .7em),
    stroke: (left: 4pt + color),
    grid(
      columns: (auto, 1fr),
      column-gutter: 1em,
      align: horizon,
      text(size: 2em, weight: "bold", fill: color)[#num],
      text(size: 1.0em, weight: "bold")[#body],
    ),
  )

  #stack(
    spacing: .7em,
    habit([1], [Sketch first, generate then.]),
    habit([2], [Split the work - keep some of it manual.]),
    habit([3], [Have a real verification strategy.]),
    habit([4], [Don't make yourself replaceable.]),
    habit([5], [Treat the AI like a colleague.]),
  )
]

#slide[
  #comment(```md
  - My favourite worked example is SQL. Sketch the query yourself,
    *then* ask the model to review and optimise. You stay in the loop;
    the model adds value without anchoring you.
  - Same for code: function signature + docstring first, body second.
```)

  = 1. Sketch first, generate then\
  #text(size: .8em, fill: gray)[You set the anchor, you stay in the loop.]

  #v(.5em)

  - Sketch the SQL query yourself, \
    #text(fill: gray)[Then ask the model to review and optimise.]
  - Write the function signature and the docstring. \
    #text(fill:gray)[Then let the model fill the body.]
  - Put `TODO` comments in your code. \
    #text(fill: gray)[Then let Claude work on them.]

  #v(0.5cm)

    #align(center)[
      #cetz.canvas(length: 1cm, {
        import cetz.draw: *

        // Lemniscate of Bernoulli, with vertical stretch for legibility:
        //   x(t) = a · cos(t) / (1 + sin²(t))
        //   y(t) = s · a · sin(t)·cos(t) / (1 + sin²(t))
        let a = 4.2
        let s = 1.1
        let pt(t) = {
          let c = calc.cos(t * 1rad)
          let n = calc.sin(t * 1rad)
          let d = 1 + n * n
          (a * c / d, s * a * n * c / d)
        }

        let manual-color = rgb("#1f77b4") // quality blue — "you"
        let gen-color    = rgb("#d9542b") // productivity orange — "model"

        // Eight phases over t ∈ [0, 2π]. Manual (short) anchors the
        // tips and the centre crossing; gen (longer) is the expansion
        // arc between anchors. Pattern: M-G-M-G-M-G-M-G.
        let TAU = 2 * calc.pi
        let phases = (
          (0.0000 * TAU, 0.0625 * TAU, "manual"),
          (0.0625 * TAU, 0.2500 * TAU, "gen"),
          (0.2500 * TAU, 0.3125 * TAU, "manual"),
          (0.3125 * TAU, 0.5000 * TAU, "gen"),
          (0.5000 * TAU, 0.5625 * TAU, "manual"),
          (0.5625 * TAU, 0.7500 * TAU, "gen"),
          (0.7500 * TAU, 0.8125 * TAU, "manual"),
          (0.8125 * TAU, 1.0000 * TAU, "gen"),
        )

        for (t0, t1, kind) in phases {
          let color = if kind == "manual" { manual-color } else { gen-color }
          let weight = if kind == "manual" { 6.5pt } else { 4.5pt }
          let n = 28
          let pts = ()
          let i = 0
          while i <= n {
            let t = t0 + (t1 - t0) * i / n
            pts.push(pt(t))
            i = i + 1
          }
          line(..pts, stroke: weight + color, mark: (end: ">", fill: color))
        }

        // Labels at the two tips.
        content(
          (-a - 0.3, 0),
          text(size: .8em, fill: manual-color, weight: "bold")[you sketch],
          anchor: "east",
        )
        content(
          (a + 0.3, 0),
          text(size: .8em, fill: gen-color, weight: "bold")[model expands],
          anchor: "west",
        )
      })
    ]
]

#slide[
  #comment(```md
  - Deliberately keep some work manual. Not for purity — for skill
    maintenance, and because the parts you do manually are the parts
    you actually understand later.
  - Small scopes also help the model: long, vague prompts get long,
    vague code back. Split, then prompt each piece.
```)

  = 2. Split the work, do some manual
  #text(size: .8em, fill: gray)[The parts you write are the parts you understand.]

  #v(.5em)

  #grid(
    columns: (1fr, auto),
    column-gutter: 2em,
    align: horizon,
    [
      - Claude does not perform well in too big scopes.  \
        #text(fill: gray)[Split tasks up and prompt them individually.]
      - Claude can help you split up work. \
        #text(fill: gray)[It just tends to work on the task right away.]
      - It is easy to lose understanding without noticing. \
        #text(fill: gray)[Keep doing important things manually!]
      - Large diffs make it easy to get lost. \
        #text(fill: gray)[Commit often so diffs stay reviewable.]
    ],
    align(center + horizon)[
      #cetz.canvas(length: 1cm, {
        import cetz.draw: *

        // Three-level tree: 1 big root → 3 sub-tasks → 6 leaves.
        // Each sub-tree gets its own colour (red / green / blue) so the
        // split is visually traceable. Nodes are rounded rects with
        // little white "title bars" inside so they read as task cards.

        let red     = rgb("#d9542b")
        let green   = rgb("#3a8f4a")
        let blue    = rgb("#1f77b4")
        let neutral = rgb("#444444")
        let subtree = (red, green, blue)

        // task-card: rounded rect with 1 or 2 white "title" lines inside.
        let card(cx, cy, w, h, fill, lines: 1) = {
          rect(
            (cx - w / 2, cy - h / 2),
            (cx + w / 2, cy + h / 2),
            fill: fill,
            stroke: none,
            radius: 0.06,
          )
          let pad = 0.1
          let inner = w - 2 * pad
          if lines == 1 {
            line(
              (cx - inner / 2, cy),
              (cx + inner / 2 - 0.04, cy),
              stroke: 1.3pt + white,
            )
          } else {
            let dy = 0.09
            line(
              (cx - inner / 2, cy + dy),
              (cx + inner / 2, cy + dy),
              stroke: 1.6pt + white,
            )
            line(
              (cx - inner / 2, cy - dy),
              (cx - inner / 2 + inner * 0.6, cy - dy),
              stroke: 1.6pt + white,
            )
          }
        }

        // Coordinates — taller than before: root at y=9, leaves at y=1.5.
        let root   = (1.5, 9.0)
        let mids   = ((0.4, 5.3), (1.5, 5.3), (2.6, 5.3))
        let leaves = (
          (0.1, 1.5), (0.7, 1.5),
          (1.2, 1.5), (1.8, 1.5),
          (2.3, 1.5), (2.9, 1.5),
        )
        let leaf-parent = (0, 0, 1, 1, 2, 2)

        let edge = rgb("#bbbbbb")

        // Connectors first so cards cap them.
        for m in mids {
          line(root, m, stroke: 1.3pt + edge)
        }
        for (i, l) in leaves.enumerate() {
          line(mids.at(leaf-parent.at(i)), l, stroke: 1pt + edge)
        }

        // Root: dark, two lines (a "big" task with multiple parts).
        card(root.at(0), root.at(1), 1.3, 0.6, neutral, lines: 2)

        // Mids: one card per subtree colour.
        for (i, m) in mids.enumerate() {
          card(m.at(0), m.at(1), 0.95, 0.45, subtree.at(i))
        }

        // Leaves: lighter shade of the parent subtree colour.
        for (i, l) in leaves.enumerate() {
          let c = subtree.at(leaf-parent.at(i)).lighten(35%)
          card(l.at(0), l.at(1), 0.5, 0.32, c)
        }
      })
    ],
  )
]

#slide[
  #comment(```md
  - This is where most teams quietly skip a step.
  - The "noise for Dart" example from our work: when you can't read
    everything the model writes, lean on automated signals — fuzz inputs,
    property tests, regressions, smoke tests on real data.
  - The point isn't "more tests". The point is: *before* you accept a
    large generated change, name the signal that would tell you it's wrong.

  If you can't say how you'd notice the bug, you don't have a verification strategy — you just have hope.
```)

  = 3. Verify strategy before code
  #text(size: .8em, fill: gray)[There are no shortcuts to quality.]
  #v(.3em)

  Before you accept a generated change, \
  #text(fill: gray)[name the signal that would tell you it's wrong.]

  #v(.8em)

  #let green = rgb("#3a8f4a")
  #let grey  = rgb("#888888")

  #let verify-card(body, color: green) = box(
    width: 100%,
    inset: (left: .8em, right: .6em, y: .5em),
    stroke: (left: 4pt + color),
    text(size: .9em, weight: "bold")[#body],
  )

  #grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: .8em,
    row-gutter: .7em,
    verify-card([Comparison against a reference implementation]),
    verify-card([Property-based tests, fuzzing, ...]),
    verify-card([Type checkers, linters, static analysers]),
    verify-card([`/review` and manual review by colleagues]),
    verify-card([Replay against real production data]),
    verify-card([Work actively on the code]),
  )

  #text(fill: gray)[#emph[Example]: Noise library for Dart — I don't speak Dart.]
]


#slide[
  #comment(```md
  - Sounds cynical but it's just practical. The replaceable parts of your
    job are the ones where you're already acting as a slow autocomplete.
    Stop doing those parts that way.
  - The work that survives is the work the model is bad at: judgement,
    context, taste, design.
```)

  = 4. Don't make yourself replaceable.
  #text(size: .8em, fill: gray)[You only get replaced if you make yourself replaceable.]

  - Code was the source of truth before, that's changing. \
    #text(fill: gray)[Now it is context given via design documents.]
  - Spend the time Claude saves you on the parts it's bad at. \
    #text(fill:gray)[Namely: decisions, judgement, context, design.]
  - Reading code is much more important now than writing code. \
    #text(fill: gray)[Keep your tools sharp. Be able to work without Claude.]

  #v(.5em)

  #align(center)[
    #cetz.canvas(length: 1cm, {
      import cetz.draw: *

      // Stack of "engineering work" bands. Bottom = AI's turf
      // (greyed). Top = yours (green). The visual story: the value
      // gradient has moved up the stack — go stand where it is now.

      let bar-w = 14.0
      let bar-h = 0.55
      let gap = 0.12

      // Bottom → top.
      let bands = (
        ([Syntax · typing · trivial lookups],         rgb("#e8e8e8"), black, [AI]),
        ([Boilerplate · scaffolding · glue],          rgb("#cdcdcd"), black, [AI]),
        ([Refactors · idioms · routine logic],        rgb("#a8a8a8"), black, [both]),
        ([Reading · understanding · review],          rgb("#5fa370"), white, [you]),
        ([Design · judgement · context · decisions],  rgb("#3a8f4a"), white, [you]),
      )

      for (i, band) in bands.enumerate() {
        let (label, fill-color, text-color, tag) = band
        let y0 = i * (bar-h + gap)
        rect(
          (0, y0),
          (bar-w, y0 + bar-h),
          fill: fill-color,
          stroke: none,
          radius: 0.08,
        )
        // Work label, left-aligned inside the band.
        content(
          (0.3, y0 + bar-h / 2),
          text(size: .75em, weight: "bold", fill: text-color)[#label],
          anchor: "west",
        )
        // Owner tag, right-aligned inside the band.
        content(
          (bar-w - 0.3, y0 + bar-h / 2),
          text(size: .7em, fill: text-color, style: "italic")[#tag],
          anchor: "east",
        )
      }

      // Upward "value" arrow alongside the stack.
      let n = bands.len()
      let stack-top = n * bar-h + (n - 1) * gap
      let arrow-x = bar-w + 0.45
      line(
        (arrow-x, 0.1),
        (arrow-x, stack-top - 0.1),
        stroke: 2pt + rgb("#3a8f4a"),
        mark: (end: ">", fill: rgb("#3a8f4a")),
      )
    })
  ]
]

#slide[
  #comment(```md
  - Collaborator, not oracle. You'd push back on a coworker — push back
    on the model. You'd ignore a coworker who hallucinated — same rule.
  - The PR-comment exchange on the slide is the behaviour: ask why, ask
    for the benchmark, refuse the hand-wave.
```)

  = 5. Treat Claude like a colleague\
  #text(size: .8em, fill: gray)[Talk to it like your seat neighbor.]

  #v(.5em)

  #let blue = rgb("#1f77b4")
  #let orange = rgb("#d9542b")
  #let border = rgb("#dddddd")

  // PR-review-style comment card: avatar (initial in coloured disc),
  // bold name + grey "commented", and the comment body underneath.
  #let pr-comment(initial, name, color, body) = box(
    width: 100%,
    inset: (x: .7em, y: .55em),
    stroke: (
      left: 3pt + color,
      top: 0.4pt + border,
      right: 0.4pt + border,
      bottom: 0.4pt + border,
    ),
    radius: 4pt,
    [
      #grid(
        columns: (auto, 1fr),
        column-gutter: .55em,
        align: horizon + left,
        box(
          width: 1.5em,
          height: 1.5em,
          fill: color,
          radius: 100%,
          inset: 0pt,
          align(
            center + horizon,
            text(size: .7em, fill: white, weight: "bold")[#initial],
          ),
        ),
        text(size: .65em)[
          #text(weight: "bold", fill: color)[#name]
          #text(fill: gray)[ commented]
        ],
      )
      #v(.15em)
      #text(size: .65em)[#body]
    ],
  )

  #grid(
    columns: (1.55fr, 1fr),
    column-gutter: 1em,
    align: horizon,
    [
      - Explain the tasks at hand like you would to a junior colleague. \
        #text(fill: gray)[A very eager, junior colleague with seemingly infinite capacity.]
      - Push back. Ask for alternatives. Let it explain. Disagree. \
        #text(fill: gray)[If you'd reject a colleague's PR for that reasoning, reject the model's.]
    ],[
      #v(-1cm)
      #stack(
      spacing: .55em,
      pr-comment("y", "you",    blue,   [Why a map here and not a for-loop?]),
      pr-comment("C", "claude", orange, [Map is more idiomatic — happy to switch if perf matters.]),
      pr-comment("y", "you",    blue,   [Show me the benchmark first.]),
    )
    ]
  )
]

#slide[
  #comment(```md
  - Peter Naur, 1985, "Programming as Theory Building". One of the most
    important short papers in the field.
  - Punchline: the code is the *artefact*. The thing that's actually
    being built is the team's shared mental model of the problem.
  - This is why handovers fail. Documentation captures the artefact,
    not the theory.
```)

  = Bonus: Programming as Theory Building
  #text(size: .8em, fill: gray)[Peter Naur, 1985]

  #v(.5em)
  #grid(
    columns: (1fr, auto),
    column-gutter: 1.5em,
    align: (left + top, right + top),
    [
      - The code is a *by-product*. What you're really building is the *theory* — your team's shared mental model of the problem.
      - Documentation captures the artefact, not the theory. The bugs, the dead ends, the "why not this?" decisions live in people's heads.
      - This is why handovers fail. The theory doesn't transfer cleanly.
    ],
    [
      #image("images/naur_bw.jpg", height: 8cm)
      #v(-.7em)
      #align(center)[
        #text(size: .55em, fill: gray)[
          Peter Naur, 1928–2016\
          Photo: Wikimedia Commons
        ]
      ]
    ],
  )
]

#slide[
  #comment(```md
  - The implication for AI is direct and uncomfortable: Claude has no
    theory. It has a snapshot of the artefact, and whatever context
    you put in front of it.
  - "Write tests for this file" → it freezes the current behaviour
    into tests, including the bugs. Because it has no theory of what
    the code *should* do.
  - Your job hasn't been automated. Your job is the theory.
  - A design doc / decision log is more useful than CLAUDE.md, because
    CLAUDE.md is size-limited. CLAUDE.md gets the headline; the design
    doc gets the reasoning.
```)

  = Bonus: What that means for Claude

  #v(.9em)

  #grid(
    columns: (4fr, 2fr),
    column-gutter: 1em,
    align: horizon,
    [
      - The model has no theory — it sees the artefact and fills the rest in. \
        #text(fill: gray)[Confidently. It won't tell you which is which.]
      - Bad prompt: "Write tests for this file" \
        #text(fill: gray)[It freezes today's behaviour, *bugs included*. Again, no mention.]
      - Your job is still to build the theory. \
        #text(fill: gray)[The AI helps you write the code that follows from it.]
    ],
    align(center + horizon)[
      #cetz.canvas(length: 1cm, {
        import cetz.draw: *

        // Venn: all context (the theory) vs what Claude sees.
        // Region labels live OUTSIDE the circles with thin leader lines
        // pointing into each region — keeps the circles uncluttered.

        let blue   = rgb("#1f77b4")
        let orange = rgb("#d9542b")
        let green  = rgb("#2ca02c")
        let dim    = rgb("#444444")
        let leader = rgb("#999999")

        let theory-c = (0, 0)
        let theory-r = 2.4
        let claude-c = (2.4, 0)
        let claude-r = 1.4

        circle(
          theory-c,
          radius: theory-r,
          fill: blue.transparentize(85%),
          stroke: 1.4pt + blue,
        )
        circle(
          claude-c,
          radius: claude-r,
          fill: orange.transparentize(78%),
          stroke: 1.4pt + orange,
        )

        // Green-tinted intersection lens, drawn over the muddy overlap.
        let ix-x = 1.99167
        let ix-y = 1.33913
        merge-path(close: true, fill: green.transparentize(60%), stroke: none, {
          arc-through(
            (ix-x, -ix-y),
            (theory-r, 0),
            (ix-x, ix-y),
          )
          arc-through(
            (ix-x, ix-y),
            (2.4 - claude-r, 0),
            (ix-x, -ix-y),
          )
        })

        // Circle titles, outside above each circle.
        content(
          (theory-c.at(0) - 0.7, theory-r + 0.35),
          text(size: .8em, weight: "bold", fill: blue)[All context],
          anchor: "south",
        )
        content(
          (claude-c.at(0) + 0.3, claude-r + 0.35),
          text(size: .8em, weight: "bold", fill: orange)[~~~~~Claude sees],
          anchor: "south",
        )

        // Callout helper: thin leader line + width-constrained label box,
        // so the three labels can't bleed into each other.
        let callout(anchor-pt, label-pt, title, body, title-color, width: 2.4cm) = {
          line(anchor-pt, label-pt, stroke: 0.7pt + leader)
          content(
            label-pt,
            anchor: "north",
            box(width: width)[
              #set text(size: .6em)
              #set par(leading: .4em)
              #align(center)[
                #text(weight: "bold", fill: title-color)[#title] \
                #text(fill: dim)[#body]
              ]
            ],
          )
        }

        // Left crescent: the unwritten theory Claude can't see.
        // Pushed further left to clear the centre callout.
        callout(
          (-1.3, -1.4),
          (-2.8, -2.4),
          [unwritten theory],
          [design decisions \ why-nots · retros \ team intuition],
          blue,
        )

        // Overlap: the artefact (what does get written down).
        // Pushed lower so it staggers below the two side callouts.
        callout(
          (1.55, -1.0),
          (1.55, -3.0),
          [the artefact],
          [code · docs \ `CLAUDE.md` · prompts],
          green,
        )

        // Right sliver: Claude's priors / guesses.
        // Pushed further right to clear the centre callout.
        callout(
          (3.3, -0.5),
          (4.9, -1.9),
          [training data],
          [average software / \ hallucinations],
          orange,
        )
      })
    ],
  )
]

#slide[
  #set align(center + horizon)
  #set page(footer: none)

  #place(left + horizon)[

  #v(2em)
  #text(size: 1.2em, fill: gray)[Questions or Disagreements?]
  #v(1em)
  #emph[Homework]:
  #v(1em)
  PROGRAMMING AS THEORY BUILDING.
  ]

  #place(right + horizon, image("images/master.jpg", height: 110%))
]
