memcpy:
	gcc -O0 memcpy.c -o memcpy-bench-0
	gcc -O1 memcpy.c -o memcpy-bench-1
	gcc -O2 memcpy.c -o memcpy-bench-2
	gcc -O3 memcpy.c -o memcpy-bench-3

	./memcpy-bench-0
	./memcpy-bench-1
	./memcpy-bench-2
	./memcpy-bench-3

employee:
	gcc -O0 employee.c -o employee-bench-0
	gcc -O1 employee.c -o employee-bench-1
	gcc -O2 employee.c -o employee-bench-2
	gcc -O3 employee.c -o employee-bench-3

	./employee-bench-0
	./employee-bench-1
	./employee-bench-2
	./employee-bench-3


matrix:
	gcc -O0 matrix.c -o matrix-bench-0
	gcc -O1 matrix.c -o matrix-bench-1
	gcc -O2 matrix.c -o matrix-bench-2
	gcc -O3 matrix.c -o matrix-bench-3

	./matrix-bench-0
	./matrix-bench-1
	./matrix-bench-2
	./matrix-bench-3
